// <auto-generated />
using System;
using Lumina_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lumina_Backend.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lumina_Backend.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(24)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Lumina_Backend.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(24)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("Lumina_Backend.Models.Security", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityQuestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Securities", (string)null);
                });

            modelBuilder.Entity("Lumina_Backend.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)");

                    b.Property<string>("TransactionDescription")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Lumina_Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("DNI")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.Property<string>("SessionToken")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(24)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DateAdded = new DateTime(2024, 4, 16, 16, 47, 53, 172, DateTimeKind.Utc).AddTicks(7497),
                            DateUpdated = new DateTime(2024, 4, 16, 16, 47, 53, 172, DateTimeKind.Utc).AddTicks(7499),
                            Email = "ajruiz2204@example.com",
                            FullName = "Alejandro Ruíz",
                            Password = "$2a$11$cOwRns/AVg34HpYY0WM/gOhJPwJr9F5GU1FwxkaaSUJY9B2t5sJoW",
                            Status = "Unverified",
                            UserName = "ajruiz2204"
                        },
                        new
                        {
                            Id = -2,
                            DateAdded = new DateTime(2024, 4, 16, 16, 47, 53, 294, DateTimeKind.Utc).AddTicks(4109),
                            DateUpdated = new DateTime(2024, 4, 16, 16, 47, 53, 294, DateTimeKind.Utc).AddTicks(4114),
                            Email = "alexanderfrt@example.com",
                            FullName = "Alexander Flores",
                            Password = "$2a$11$9u2GdVuHcfbcnvsP7xfR1u5s/P8sqY6plv2mD20vnHIuui0H0HJpu",
                            Status = "Unverified",
                            UserName = "AlexanderFRT"
                        },
                        new
                        {
                            Id = -3,
                            DateAdded = new DateTime(2024, 4, 16, 16, 47, 53, 422, DateTimeKind.Utc).AddTicks(2746),
                            DateUpdated = new DateTime(2024, 4, 16, 16, 47, 53, 422, DateTimeKind.Utc).AddTicks(2752),
                            Email = "4rnol@example.com",
                            FullName = "Arnol Flores",
                            Password = "$2a$11$ZGzVYGF39NOP/0VFSbn2D.dPW.lFG4s3wz.fuANLgIh9cmYcrHExm",
                            Status = "Unverified",
                            UserName = "4rnol"
                        },
                        new
                        {
                            Id = -4,
                            DateAdded = new DateTime(2024, 4, 16, 16, 47, 53, 541, DateTimeKind.Utc).AddTicks(6846),
                            DateUpdated = new DateTime(2024, 4, 16, 16, 47, 53, 541, DateTimeKind.Utc).AddTicks(6849),
                            Email = "ema_ramirez@example.com",
                            FullName = "Emanuel Ramirez",
                            Password = "$2a$11$KeB9enSHQPL4nKKbes7Sj.an4BSroNJsbtnL4JxaBSSBTkVnB.vKi",
                            Status = "Unverified",
                            UserName = "ema_ramirez"
                        },
                        new
                        {
                            Id = -5,
                            DateAdded = new DateTime(2024, 4, 16, 16, 47, 53, 660, DateTimeKind.Utc).AddTicks(7302),
                            DateUpdated = new DateTime(2024, 4, 16, 16, 47, 53, 660, DateTimeKind.Utc).AddTicks(7306),
                            Email = "ezealeguzman@example.com",
                            FullName = "Ezequiel Guzman",
                            Password = "$2a$11$Gb7NtGIspAnvK6IpAU1iD.IkLq4Mtte.g7ntaJ74i00ppnLbVtLZG",
                            Status = "Unverified",
                            UserName = "ezealeguzman"
                        },
                        new
                        {
                            Id = -6,
                            DateAdded = new DateTime(2024, 4, 16, 16, 47, 53, 781, DateTimeKind.Utc).AddTicks(3148),
                            DateUpdated = new DateTime(2024, 4, 16, 16, 47, 53, 781, DateTimeKind.Utc).AddTicks(3156),
                            Email = "facu597@example.com",
                            FullName = "Facundo Castro",
                            Password = "$2a$11$Uv/f9eR4yxaGFiZHIC0MkeKq9LsxLyCLoirL/thSDyKmhPeY1AioK",
                            Status = "Unverified",
                            UserName = "facu597"
                        },
                        new
                        {
                            Id = -7,
                            DateAdded = new DateTime(2024, 4, 16, 16, 47, 53, 897, DateTimeKind.Utc).AddTicks(2636),
                            DateUpdated = new DateTime(2024, 4, 16, 16, 47, 53, 897, DateTimeKind.Utc).AddTicks(2639),
                            Email = "giolucc@example.com",
                            FullName = "Giovanni Lucchetta",
                            Password = "$2a$11$86YO7MPaCmi0cLRDx3LA/OMhCz5L8bNYFZwtadMn9WuVth5lyvMNu",
                            Status = "Unverified",
                            UserName = "giolucc"
                        },
                        new
                        {
                            Id = -8,
                            DateAdded = new DateTime(2024, 4, 16, 16, 47, 54, 14, DateTimeKind.Utc).AddTicks(400),
                            DateUpdated = new DateTime(2024, 4, 16, 16, 47, 54, 14, DateTimeKind.Utc).AddTicks(404),
                            Email = "karla6524@example.com",
                            FullName = "Karla Chavez",
                            Password = "$2a$11$zSeH32RcoW6wBoI77Liw2e5JDfYfc2QePKGVZwtfKgd/BzUuj/l96",
                            Status = "Unverified",
                            UserName = "karla6524"
                        },
                        new
                        {
                            Id = -9,
                            DateAdded = new DateTime(2024, 4, 16, 16, 47, 54, 129, DateTimeKind.Utc).AddTicks(8612),
                            DateUpdated = new DateTime(2024, 4, 16, 16, 47, 54, 129, DateTimeKind.Utc).AddTicks(8617),
                            Email = "mabel8750_@example.com",
                            FullName = "Mabel Ceballos",
                            Password = "$2a$11$Y1bSqAXhMhAr1IcLduoZW.I8Rq1URxUfUGd9KTsojka.GwsbL9Gei",
                            Status = "Unverified",
                            UserName = "mabel8750_"
                        });
                });

            modelBuilder.Entity("Lumina_Backend.Models.Account", b =>
                {
                    b.HasOne("Lumina_Backend.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lumina_Backend.Models.Log", b =>
                {
                    b.HasOne("Lumina_Backend.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lumina_Backend.Models.Security", b =>
                {
                    b.HasOne("Lumina_Backend.Models.User", "User")
                        .WithMany("Securities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lumina_Backend.Models.Transaction", b =>
                {
                    b.HasOne("Lumina_Backend.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Lumina_Backend.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Lumina_Backend.Models.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Logs");

                    b.Navigation("Securities");
                });
#pragma warning restore 612, 618
        }
    }
}
